version: "3.9"
services:
  bridge:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/Bridge"
      SPRING_DATASOURCE_USERNAME: "Bridge_Postgre"
      SPRING_DATASOURCE_PASSWORD: "Bridge_Password1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "Bridge"
      POSTGRES_USER: "Bridge_Postgre"
      POSTGRES_PASSWORD: "Bridge_Password1234"
    ports:
      - "5432:5432"