spring.datasource.url=jdbc:postgresql://localhost:5432/Bridge
spring.datasource.username=Bridge_Postgre
spring.datasource.password=Bridge_Password1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
server.port=8081
logging.level.org.springframework.security=trace

jwt.secret.access=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==